// Generated by tools/build-notepad.ps1 from config.js - do not edit, edit config.js.
globalThis.VoiceTypeLanguages = [
  /*
   * The rule: we dictate in the languages we are published in, plus the large languages
   * whose speakers have no reasonable substitute.
   *
   * That is the 52 store locales, one recognition tag each; the regional variants the
   * store itself splits (Spanish, Portuguese, Chinese); five Englishes; and fourteen
   * languages added back on 2026-09-10 for size and for lack of an alternative - Punjabi,
   * Urdu, Cantonese, Javanese, Burmese, Sundanese, Uzbek, Azerbaijani, Nepali, Zulu,
   * Sinhala, Khmer, Kazakh, Afrikaans.
   *
   * The list was briefly 131, from "add everything Chrome supports", and that produced a
   * menu where a Ukrainian speaker scrolled past Basque, Sundanese and Icelandic to reach
   * their own language. What went for good: regional duplicates that differ only by accent
   * (Arabic in 13 countries, Spanish in 20, French in 4, German in 3, and doubles of
   * Dutch, Italian, Tamil and Urdu).
   *
   * Still out, and worth revisiting: Albanian, Armenian, Georgian, Mongolian. Not huge,
   * but each is a language of its own with no near substitute. Adding one is a line.
   *
   * Ordering: English (US) is pinned first, being the default and the commonest choice.
   * Everything after it is alphabetical by label, the other Englishes included - grouping
   * the variants at the top would put four entries nobody speaks above the one they do.
   *
   * Badges: the language code, plus the country where a language appears more than once.
   * Bare country codes do not survive this list: Arabic and Argentina both want AR,
   * Catalan and Canada both want CA. config.test.html enforces uniqueness.
   */
  { code: 'en-US', short: 'EN', label: 'English (US)', commands: true },

  { code: 'af-ZA', short: 'AF', label: 'Afrikaans' },
  { code: 'am-ET', short: 'AM', label: 'Amharic', unverified: true },
  { code: 'ar-SA', short: 'AR', label: 'Arabic' },
  { code: 'az-AZ', short: 'AZ', label: 'Azerbaijani' },
  { code: 'bn-BD', short: 'BN', label: 'Bengali' },
  { code: 'bg-BG', short: 'BG', label: 'Bulgarian' },
  { code: 'my-MM', short: 'MY', label: 'Burmese' },
  // Its own language, not an accent of Mandarin, and Google gives it its own tag. Keeping
  // the two apart is the whole point of having it.
  { code: 'yue-Hant-HK', short: 'YUE', label: 'Cantonese' },
  { code: 'ca-ES', short: 'CA', label: 'Catalan' },
  // Google's own tags for Mandarin are cmn-*, not zh-*.
  { code: 'cmn-Hans-CN', short: 'ZH', label: 'Chinese (Simplified)' },
  { code: 'cmn-Hant-TW', short: 'ZH쨌TW', label: 'Chinese (Traditional)' },
  { code: 'hr-HR', short: 'HR', label: 'Croatian' },
  { code: 'cs-CZ', short: 'CS', label: 'Czech' },
  { code: 'da-DK', short: 'DA', label: 'Danish' },
  { code: 'nl-NL', short: 'NL', label: 'Dutch' },

  /*
   * Five Englishes. The tag changes the accent model AND the spelling, so a British user
   * on en-US gets "color" in every email and an Indian accent is recognized measurably
   * worse by the American model. These are the large English-writing markets; the other
   * ten Google offers were noise in the menu.
   */
  { code: 'en-AU', short: 'EN쨌AU', label: 'English (Australia)', commands: true },
  { code: 'en-CA', short: 'EN쨌CA', label: 'English (Canada)', commands: true },
  { code: 'en-IN', short: 'EN쨌IN', label: 'English (India)', commands: true },
  { code: 'en-GB', short: 'EN쨌GB', label: 'English (UK)', commands: true },

  { code: 'et-EE', short: 'ET', label: 'Estonian', unverified: true },
  { code: 'fil-PH', short: 'FIL', label: 'Filipino' },
  { code: 'fi-FI', short: 'FI', label: 'Finnish' },
  { code: 'fr-FR', short: 'FR', label: 'French' },
  { code: 'de-DE', short: 'DE', label: 'German' },
  { code: 'el-GR', short: 'EL', label: 'Greek' },
  { code: 'gu-IN', short: 'GU', label: 'Gujarati' },
  { code: 'he-IL', short: 'HE', label: 'Hebrew', unverified: true },
  { code: 'hi-IN', short: 'HI', label: 'Hindi' },
  { code: 'hu-HU', short: 'HU', label: 'Hungarian' },
  { code: 'id-ID', short: 'ID', label: 'Indonesian' },
  { code: 'it-IT', short: 'IT', label: 'Italian' },
  { code: 'ja-JP', short: 'JA', label: 'Japanese' },
  { code: 'jv-ID', short: 'JV', label: 'Javanese' },
  { code: 'kn-IN', short: 'KN', label: 'Kannada' },
  { code: 'kk-KZ', short: 'KK', label: 'Kazakh' },
  { code: 'km-KH', short: 'KM', label: 'Khmer' },
  { code: 'ko-KR', short: 'KO', label: 'Korean' },
  { code: 'lv-LV', short: 'LV', label: 'Latvian', unverified: true },
  { code: 'lt-LT', short: 'LT', label: 'Lithuanian', unverified: true },
  { code: 'ms-MY', short: 'MS', label: 'Malay' },
  { code: 'ml-IN', short: 'ML', label: 'Malayalam' },
  { code: 'mr-IN', short: 'MR', label: 'Marathi' },
  { code: 'ne-NP', short: 'NE', label: 'Nepali' },
  // The store locale is "no"; there is no such recognition tag - Bokmal is the one that
  // exists.
  { code: 'nb-NO', short: 'NO', label: 'Norwegian (Bokmal)' },
  { code: 'fa-IR', short: 'FA', label: 'Persian' },
  { code: 'pl-PL', short: 'PL', label: 'Polish' },
  { code: 'pt-BR', short: 'PT쨌BR', label: 'Portuguese (Brazil)' },
  { code: 'pt-PT', short: 'PT', label: 'Portuguese (Portugal)' },
  // The script is in the label deliberately. Google's tag is Gurmukhi as written in
  // India; Punjabi in Pakistan uses Shahmukhi and is NOT covered by it. Calling this
  // plain "Punjabi" would promise half its speakers something they will not get.
  { code: 'pa-Guru-IN', short: 'PA', label: 'Punjabi (Gurmukhi)' },
  { code: 'ro-RO', short: 'RO', label: 'Romanian' },
  { code: 'ru-RU', short: 'RU', label: 'Russian', commands: true },
  { code: 'sr-RS', short: 'SR', label: 'Serbian' },
  { code: 'si-LK', short: 'SI', label: 'Sinhala' },
  { code: 'sk-SK', short: 'SK', label: 'Slovak' },
  { code: 'sl-SI', short: 'SL', label: 'Slovenian', unverified: true },
  { code: 'es-MX', short: 'ES쨌MX', label: 'Spanish (Latin America)' },
  { code: 'es-ES', short: 'ES', label: 'Spanish (Spain)' },
  { code: 'su-ID', short: 'SU', label: 'Sundanese' },
  { code: 'sw-TZ', short: 'SW', label: 'Swahili' },
  { code: 'sv-SE', short: 'SV', label: 'Swedish' },
  { code: 'ta-IN', short: 'TA', label: 'Tamil' },
  { code: 'te-IN', short: 'TE', label: 'Telugu' },
  { code: 'th-TH', short: 'TH', label: 'Thai' },
  { code: 'tr-TR', short: 'TR', label: 'Turkish' },
  { code: 'uk-UA', short: 'UA', label: 'Ukrainian' },
  { code: 'ur-PK', short: 'UR', label: 'Urdu' },
  { code: 'uz-UZ', short: 'UZ', label: 'Uzbek' },
  { code: 'vi-VN', short: 'VI', label: 'Vietnamese' },
  { code: 'zu-ZA', short: 'ZU', label: 'Zulu' },
];;